version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - data:/app/data
    environment:
      - DATABASE_URL=${DATABASE_URL:-sqlite:///./data/genai_labeling.db}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-in-production}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:3001,http://frontend:3001}
      - PYTHONPATH=/app/src
    env_file:
      - .env
    depends_on: []
    networks:
      - app-network

  frontend:
    build: 
      context: ./frontend
      args:
        - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8000}
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://localhost:8000}
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data:
